version: '3.8'
services:
  docker-react-app:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    image: docker-react
    volumes:
      - ..:/app
      - /app/node_modules
      - /app/docker
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WDS_SOCKET_HOST=127.0.0.1
      - WATCHPACK_POLLING=true
    command: npm start