version: '3.8'
services:
  docker-vue-app:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    image: docker-vue
    volumes:
      - ..:/app
      - /app/node_modules
      - /app/docker
    ports:
      - "8080:8080"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WDS_SOCKET_HOST=127.0.0.1
      - WATCHPACK_POLLING=true
    command: npm run serve