---
name: checks
on: [push]
jobs:
  test-lint:
    name: test and lint
    runs-on: ubuntu-20.04
    steps:
      - name: login into docker hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: checkout
        uses: actions/checkout@v2
      - name: test
        run: docker-compose run -f .docker/docker-compose.yml --rm app sh -c "python -m unittest discover"
      - name: lint
        run: docker-compose run -f .docker/docker-compose.yml --rm app sh -c "flake8"